# Generated by Django 4.1 on 2022-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Пользователь"
            ),
        ),
    ]
