# Generated by Django 4.1.3 on 2022-11-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_rename_user_like_like_dislikes_userlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.CharField(default=None, max_length=5000, verbose_name="Фото"),
        ),
    ]
