# Generated by Django 4.1 on 2022-10-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_videos_name_video"),
    ]

    operations = [
        migrations.RemoveField(model_name="like_dislikes", name="dis_likes",),
        migrations.AddField(
            model_name="like_dislikes",
            name="dislikes",
            field=models.IntegerField(default=0, verbose_name="Дизлайки"),
        ),
        migrations.AlterField(
            model_name="like_dislikes",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="Лайки"),
        ),
    ]
