# Generated by Django 4.1 on 2022-10-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_remove_like_dislikes_dis_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="name_video",
            field=models.CharField(max_length=200, verbose_name="Название видео"),
        ),
    ]
