# Generated by Django 4.1 on 2022-10-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_videos_name_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="href",
            field=models.CharField(max_length=1000, verbose_name="Ссылка_на_Видео"),
        ),
    ]
