# Generated by Django 4.1 on 2022-10-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_videos_href"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videos", old_name="Описание_к_Видео", new_name="title",
        ),
    ]
