# Generated by Django 4.1 on 2022-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_rename_описание_к_видео_videos_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(default=None, upload_to="", verbose_name="Фото"),
        ),
    ]
