# Generated by Django 4.1 on 2022-10-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Пользователь"
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="Пароль")),
                ("photo", models.ImageField(upload_to="", verbose_name="Фото")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_video",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название видео"
                    ),
                ),
                (
                    "Описание_к_Видео",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Описание к видео",
                    ),
                ),
                (
                    "href",
                    models.CharField(max_length=100, verbose_name="Ссылка_на_Видео"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.user",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео",},
        ),
        migrations.CreateModel(
            name="Like_DisLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.IntegerField(default=None, verbose_name="Лайки")),
                (
                    "dis_likes",
                    models.IntegerField(default=None, verbose_name="Дизлайки"),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.videos",
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайки и Дизлайки",
                "verbose_name_plural": "Лайки и Дизлайки",
            },
        ),
    ]
