# Generated by Django 4.1 on 2022-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news", name="title", field=models.CharField(max_length=250),
        ),
    ]
