# Generated by Django 4.1 on 2022-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_photo_user_delete_news_photo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="email_user", field=models.CharField(max_length=20),
        ),
    ]
