# Generated by Django 4.1 on 2022-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_user_email_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
