# Generated by Django 4.1 on 2022-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo", name="photo", field=models.CharField(max_length=100),
        ),
    ]
